### ISSUE TITLE
Manager for Recovery

### ISSUE THREAD

**Issue by 6xthFNGR** [programminghoch10/Lygisk#19]
Hey,

the usual Magisk Manager for Recovery Module wont work, my installation fails instantly.
I could imagine why, and guess its due to different file systems.
So asking the dev for the Module may not be suitable, thats why I ask here:

Any way to Manage Lygisk from Recovery via adb?
(@Linux4 I use LOS Recovery and some File Based Encryption device, so there is no way for me to use the Recovery and mount/decrypt the system/data and manipulate in there from Recovery. I may try via adb shell but that would require constant activation of USB Debugging, so a security risk - which is why some Recovery based manipulation to atleast deactivate Lygisk would be great).

Thanks

Ps.: If have not narrowed down the problem properly I am happy to receive advise how to understand the situation.

EDIT: Okay after using https://themagisk.com/magisk-manager-for-recovery-mode/ which fails to install,
 I found https://github.com/Rikj000/Magisk-Manager-for-Recovery-Mode/releases which installs fine. So it was no filesystem issue but just the version issue.
Hard to find .
Anyways: The Module wont work as expected.

I still end up with the issue that my Phone, with LOS Recovery (your lates LOSRecovery 12.1 for SamsungGalaxyS10+/G975) and FBE(knox) + activated USB Debugging + Root Debugging + Host Device RSA Key accepted wont work as expected: I start LOS Recovery and mount the system and ADB sideload, but have no ADB shell access to the system.
I can ls and cd to my sdcard, but there is no mm folder in there.
Also, any other system access wont work - f.e. pm.

How to get adb root access to the system?
How to decryopt/mount the system with the LOS Recovery?
I know thats less Lygisk than LOS Recovery, but I just ask here. If you like me to repost it at some LOS Recovery threat in XDA just go ahead

**Comment by binarynoise** [comment]
> How to decryopt/mount the system with the LOS Recovery?

You don't. It doesn't work. I tried. You can't decrypt /data.

> I may try via adb shell but that would require constant activation of USB Debugging, so a security risk.

No, it's not. To authorize a new PC to allow adb connection, your phone needs to be unlocked, so it's protected by your password. If you don't disable the timeout, adb authorizations will be reset every few days so you need to authorize agian.

> I start LOS Recovery and mount the system and ADB sideload, but have no ADB shell access to the system.

You need to enable adb in LOS Recovery under Advanced → Enable adb

> I can ls and cd to my sdcard, but there is no mm folder in there.

/data isn't mounted so /sdcard (which is a symlink to /data/media/0) is not available
