### ISSUE TITLE
Lygisk App: "Requires Additional Setup"

### ISSUE THREAD

**Issue by dumdedumda** [programminghoch10/Lygisk#26]
When opening the Lygisk app, Zygisk status displays "No." Additionally, app pops up with error: "Requires Additional Setup... Your device needs reflash Magisk to work properly. Please reinstall Magisk within app, recovery module cannot get correct device info." 

Is this normal? Or should I proceed with the "Direct Install"? 

First time migrating from Magisk to Lygisk, so a bit lost. Additionally, Google search results is confusing "Lygisk" with "Magisk" so can't get the correct search results.

Edit: Should add some context: I installed Lygisk via LineageOS recovery. Also factory reset/wiped device before doing so.

**Comment by RealStickman** [comment]
I'm having this issue as well. Just installed Lygisk 26.1 through the LineageOS recovery.  
Root seems to work with the programs I tested.  
Is this a bug with the Manager or am I doing something wrong?

**Comment by programminghoch10** [comment]
@RealStickman this a new requirement by magisk
just do what the prompt says and restart then it should work until next system update
we already fixed this, will be deployed with the next update of Lygisk
