### ISSUE TITLE
Allow patch boot in app

### ISSUE THREAD

**Issue by commonuserlol** [programminghoch10/Lygisk#29]
Hi, Some mediatek devices have restrictions to flash boot partition in system, read-only fs, etc. direct install not working. Since 26.1 magisk requires install from system (direct or patch boot) i need to build lygisk manually to fix that. Can you revert https://github.com/programminghoch10/Lygisk/commit/4e55ead8676da010578fa70bce49d522e43ecb1f or parent commit?

**Comment by binarynoise** [comment]
Lygisk supports only direct install or installation through recovery.
If you need to patch boot, you need to use Magisk.

You could also try to manually do this: <https://github.com/programminghoch10/Lygisk/blob/613a0259dac74860ab8f29e1f5b5ae5848b3b629/app/src/main/java/com/topjohnwu/magisk/core/tasks/MagiskInstaller.kt#L196>, then install again from recovery. Direct install shouldn't be necessary anymore.

**Comment by commonuserlol** [comment]
Installing from recovery causes dialog with "Magisk should be reflashed since recovery mode can't get device info" or smth. Direct install don't working (above i said why), so

**Comment by binarynoise** [comment]
Did you read the code snippet? Did you read my comment that if you run that, that warning won't show?
