### ISSUE TITLE
[request] Beta branch is out of date

### ISSUE THREAD

**Issue by moghingold** [programminghoch10/Lygisk#30]
Currently the latest Beta build of Lygisk is 26300. However, some LSposed modules, like Shamiko, require 26302 or greater. Build 26302 is the current beta build of upstream Magisk. 

Does Lygisk have a release schedule for how often it tracks available updates from upstream Magisk beta? Very understandable if not, given that this is a hobby fork for a very limited number of devices that Magisk will (hopefully, someday) incorporate into its own supported edge cases.

**Comment by programminghoch10** [comment]
cant even wait one night for the CI to run
