### ISSUE TITLE
Install to inactive slot (After OTA)

### ISSUE THREAD

**Issue by BugReportI** [programminghoch10/Lygisk#32]
I cannot select this option in Lygisk 26.4 latest stable after updating OS.

This option is really useful so I do not have to flash Lygisk in recovery in LineageOS.after update.

Device: Sony Xperia 1 III
OS: Latest official LineageOS build

**Comment by binarynoise** [comment]
Lygisk is for A-only. Use Magisk

**Comment by BugReportI** [comment]
> Lygisk is for A-only. Use Magisk

Thanks, I was a bit confused thinking Lygisk was for all devices if on custom rom.

**Comment by binarynoise** [comment]
You may want to read https://github.com/programminghoch10/Lygisk#lygisk-vs-magisk

**Comment by BugReportI** [comment]
> You may want to read https://github.com/programminghoch10/Lygisk#lygisk-vs-magisk

Yeah I reread that and it seems much more clearer what Lygisk if for, than last I read it.
