### ISSUE TITLE
Lygisk version 26.1 - where to download?

### ISSUE THREAD

**Issue by mangoheini** [programminghoch10/Lygisk#33]
Hi together,
first of all many thanks for your efforts! I've been happy Lygisk user for some years. :smiley:

Today I updated LOS 18.1 Lygisk on a long time unused device, to find out that it bootloops with all available Lygisk versions.

So I tried upstream Magisk and found, that all versions > 26.1 also bootloop. Magisk 26.1 works fine but of course doesn't survive LOS updates. :yum: 

Would you please point me to the download of Lygisk 26.1? Maybe I'm blind, but I cannot find a Releases page. :see_no_evil: 

Thank you very much! :smiley:

**Comment by binarynoise** [comment]
Hi,
We only offer downloads of the current version and do not archive old ones.

You would need to build it yourself.
