### ISSUE TITLE
Current state with Android 14/LineageOS 21 and latest Magisk?

### ISSUE THREAD

**Issue by KlausHans** [programminghoch10/Lygisk#38]
Hello, i am not deep in the topic, more like only an end user. Is Lygisk still needed with the latest LineageOs 21 and Magisk?
Thanks!

**Comment by programminghoch10** [comment]
This depends on your device, not on the android version.
Lygisk is only needed on A-only devices.

**Comment by KlausHans** [comment]
Ah, thanks, i forgot this. I have a Galaxy S10+, so Lygisk it is.

Thanks again!
