### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by kp-emagine** [programminghoch10/Lygisk#5]
""We recommend installation via recovery. Just rename the downloaded file to .zip and sideload it.""
Receives an error: Signature Verification failed E:error: 21

This is attempting to rename the downloaded .apk to .zip

**Comment by kp-emagine** [comment]
I do see the option to apply/install anyways... but, this may be a deterrent for anyone else.  Is there any way to correct it?

**Comment by programminghoch10** [comment]
This is normal and expected, you just have to install anyways.
